### ISSUE TITLE
Revisit whether we can use the parent documentation configuration for Data Builder

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/databuilder#1022]
This currently doesn't work due to a TypeError in the configuration:

```
TypeError: typing.Union cannot be used with isinstance()
```

This should disappear in Python 3.10, if MkDocs or the multirepo plugin don't ever get a patch to fix this.

Even with that patched out, the configuration is still a problem due to the macros plugin:

```
Traceback (most recent call last):
  File "…/mkdocs_macros/plugin.py", line 156, in variables
    return self._variables
AttributeError: 'MacrosPlugin' object has no attribute '_variables'

During handling of the above exception, another exception occurred:
…
  File "…/mkdocs_macros/plugin.py", line 633, in on_nav
    self.variables['navigation'] = nav
  File "…/mkdocs_macros/plugin.py", line 158, in variables
    raise AttributeError("Property called before on_config()")
AttributeError: Property called before on_config()
```

**Comment by StevenMaude** [comment]
Closing in favour of #978.
