### ISSUE TITLE
Long-running gentests fail in CI with `sqlite3.OperationalError: database table is locked`

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#1180]
We get this failure _almost_, but not quite, every time they run at present.

The first time we saw this was against this commit: https://github.com/opensafely-core/databuilder/commit/f0a3009aac8ecfa17ceb1d3a28df9256ea748413
The previous successful commit was: https://github.com/opensafely-core/databuilder/commit/30d703818f90a2f251d608749f38433a7aa31ef7
The diff is [here](https://github.com/opensafely-core/databuilder/compare/30d703818f90a2f251d608749f38433a7aa31ef7...f0a3009aac8ecfa17ceb1d3a28df9256ea748413) which contains quite a few changes, including the switch to Python 3.11.

An example error:
```
Traceback (most recent call last):
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1933, in _exec_single_context
    self.dialect.do_executemany(
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 745, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.OperationalError: database table is locked: p0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/databuilder/databuilder/tests/generative/test_query_model.py", line 258, in run_with
    engine.setup(instances, metadata=sqla_metadata)
  File "/home/runner/work/databuilder/databuilder/tests/conftest.py", line 161, in setup
    return self.database.setup(*items, metadata=metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/databuilder/databuilder/tests/lib/databases.py", line 96, in setup
    session.bulk_save_objects(input_data)
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4389, in bulk_save_objects
    self._bulk_save_mappings(
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4559, in _bulk_save_mappings
    with util.safe_reraise():
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 147, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 4548, in _bulk_save_mappings
    bulk_persistence._bulk_insert(
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/orm/bulk_persistence.py", line 176, in _bulk_insert
    result = persistence._emit_insert_statements(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/orm/persistence.py", line 1020, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
           ^^^^^
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1933, in _exec_single_context
    self.dialect.do_executemany(
  File "/home/runner/work/databuilder/databuilder/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 745, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database table is locked: p0
[SQL: INSERT INTO p0 (patient_id, i1, i2, b1, b2, d1, d2, f1, f2, s1, s2) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: [(8, 3, 10, 0, 0, '2012-10-12', '2016-11-06', 11.0, 11.0, 'a', ''), (2, 6, 8, 1, 0, '2020-11-01', '2020-09-17', 1.5, 0.0, 'cac', ''), (4, 5, 10, 0, 1, '2012-11-14', '2019-08-24', 11.0, 0.0, 'b', 'ca')]]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

Workflow run:
https://github.com/opensafely-core/databuilder/actions/runs/4592556320/jobs/8109691775#step:4:2069

Log file:
[`actions-runs-4592556320-jobs-8109691775.txt`](https://github.com/opensafely-core/databuilder/files/11147640/actions-runs-4592556320-jobs-8109691775.txt)

**Comment by evansd** [comment]
I tried reproducing this locally and couldn't with 1,000 examples but could with 10,000:
```
GENTEST_EXAMPLES=10 pytest tests/generative
```

Interestingly, once I'd hit the error all subsequent generative tests fail immediately with the same error – regardless of the number of examples. This suggests something is being persisted to disk which shouldn't be.

**Comment by evansd** [comment]
Wahoo! It's a proper Heisenbug! The test runs fine with the following `print` statement in place. It fails again immediately if I comment it out.
```py
@hyp.given(variable=variable_strategy, data=data_strategy)
@hyp.settings(**settings)
def test_query_model(query_engines, variable, data, recorder):
    print("wat")
    recorder.record_inputs(variable, data)
    run_test(query_engines, data, variable, recorder)
```

This is not coincidence. I can reliably switch between success and failure by commenting and uncommenting this `print` statement.

**Comment by evansd** [comment]
This turned out to be the interaction of two different issues:

1. I added an IGNORED_ERRORS entry for negative ISO dates (i.e. BC dates) which we can't handle in Python and don't care about:
   https://github.com/opensafely-core/databuilder/blob/632bb89380788f57d2b8450b7acbf60b997f9ffd/tests/generative/test_query_model.py#L239-L240
   However, unlike positive dates these **don't always use four digits for the year** e.g. we sometimes see `-004-02-13`. When we get one of these dates the regex doesn't match so the error isn't ignored and Hypothesis thinks it has found a bug.

2. This error is raised during the course of converting a row of database results into Python objects. When we hit the error we **stop consuming any more results**.

3. The cursor containing the remainder of the results now sits around waiting to be consumed (or garbage collected).

4. Because of the way shared, in-memory SQLite databases work (and possibly because we haven't changed the default configuration) this cursor ends up holding a lock on the tables it's reading from.

5. This means that the next time we try to run a query we get a `database table is locked` error.

6. This means that when Hypothesis tries to shrink the test case it starts getting different errors from the one it originally got (`OperationalError` as opposed to `ValueError`). This makes it very upset.

Fixing the regex is easy enough. And I think the general fix for the second issue is to explicitly close the cursor if we encounter an error.
