### ISSUE TITLE
Investigate why generative tests didn't hit in-memory database bug

### ISSUE THREAD

**Issue by evansd** [opensafely-core/databuilder#477]
As of the time of writing (commit a4b44a8b188b19b9a63df55c29d13bd07ca67073) the in-memory engine fails this test while the SQLite engine passes it:
```py
def test_two_filters(spec_test):
    table_data = {
        e: """
              | i1 | b1
            --+----+----
            1 | 1  | T
            1 | 2  | T
            1 | 3  | F
            """,
    }

    spec_test(
        table_data,
        e.take(e.i1 >= 2).take(e.b1).i1.sum_for_patient(),
        {
            1: 2,
        },
    )
```

It follows that this construct was never produced by the generative tests. But it doesn't seem a terribly complicated one, so it would be good to understand why this wasn't produced and whether we can change this. It's possible that some limitation in the generative tests is causing us to miss large chunks of query space.

Slack thread:
https://bennettoxford.slack.com/archives/C02LEF2GC75/p1652172229819099

**Comment by benbc** [comment]
Here is a branch which modifies the generative tests such that problems like this can be reproduced.

https://github.com/opensafely-core/databuilder/tree/benbc/reduce-query-space

There are three changes here:

1. Removing all the operators from the variable strategy other than those in the failing query.
2. Changing the data setup so there is only one event table.
3. Change the column schema so it just has one integer and one boolean column.

The intention of these changes was to reduce the query space to be explored to make it more likely that we hit the problematic queries -- based on the hypothesis that the only reason we haven't seen this before is that the query space may be too big.

It seems conceivable that something about 2 (or, less likely, 3) has changed things so that it's not just a reduction in the query space.

**Comment by evansd** [comment]
For whatever reason, following the refactoring in #586, the generative tests now expose this bug.
```
EXAMPLES=5000 pytest tests/generative/test_query_model.py::test_query_model
```
```
=========================================================== test session starts ============================================================
platform linux -- Python 3.9.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/dave/projects/ebmdatalab/databuilder, configfile: pyproject.toml
plugins: mock-3.8.1, freezegun-0.4.2, cov-3.0.0, hypothesis-6.47.5, subtests-0.8.0
collected 1 item                                                                                                                           

tests/generative/test_query_model.py F                                                                                               [100%]

================================================================= FAILURES =================================================================
_____________________________________________________________ test_query_model _____________________________________________________________
Traceback (most recent call last):
  File "/home/dave/projects/ebmdatalab/databuilder/tests/generative/test_query_model.py", line 65, in test_query_model
    @hyp.settings(**settings)
  File "/home/dave/.virtualenvs/ebm-databuilder/lib/python3.9/site-packages/hypothesis/core.py", line 1237, in wrapped_test
    raise the_error_hypothesis_found
  File "/home/dave/projects/ebmdatalab/databuilder/tests/generative/test_query_model.py", line 69, in test_query_model
    run_test(query_engines, data, variable)
  File "/home/dave/projects/ebmdatalab/databuilder/tests/generative/test_query_model.py", line 91, in run_test
    assert (
AssertionError: Mismatch between in_memory and sqlite
assert [{'patient_id..., 'v': False}] == [{'patient_id': 1, 'v': True}]
  At index 0 diff: {'patient_id': 1, 'v': False} != {'patient_id': 1, 'v': True}
  Use -v to get more diff
---------------------------------------------------------------- Hypothesis ----------------------------------------------------------------
Highest target score: -29  (label='')

Falsifying example: test_query_model(
    variable=AggregateByPatient.Exists(source=Filter(source=Filter(source=SelectTable(name='e0', schema=TableSchema(i1=int, i2=int, b1=bool, b2=bool)), condition=SelectColumn(source=SelectTable(name='e0', schema=TableSchema(i1=int, i2=int, b1=bool, b2=bool)), name='b1')), condition=SelectColumn(source=SelectTable(name='e0', schema=TableSchema(i1=int, i2=int, b1=bool, b2=bool)), name='b1'))),
    data=[{'type': tests.lib.util.E0,
      'patient_id': 1,
      'i1': 0,
      'i2': 0,
      'b1': False,
      'b2': False},
     {'type': tests.lib.util.E0,
      'patient_id': 1,
      'i1': 0,
      'i2': 0,
      'b1': True,
      'b2': False}],
    query_engines={'in_memory': <tests.conftest.QueryEngineFixture at 0x7fabc64f12b0>,
     'sqlite': <tests.conftest.QueryEngineFixture at 0x7fabc64f1490>,
     'mssql': <tests.conftest.QueryEngineFixture at 0x7fabc64c8610>},
)
========================================================= short test summary info ==========================================================
FAILED tests/generative/test_query_model.py::test_query_model - AssertionError: Mismatch between in_memory and sqlite
====================================================== 1 failed in 658.66s (0:10:58) =======================================================
```

**Comment by benbc** [comment]
@evansd I don't think we're ever going to decide that following this up is the best use of our time, so I'm going to close this. Please reopen if you disagree.
