### ISSUE TITLE
Remove unhelpful output from error messages

### ISSUE THREAD

**Issue by inglesp** [opensafely-core/databuilder#533]
To generate a dataset, we [import a module containing a dataset definition](https://github.com/opensafely-core/databuilder/blob/main/databuilder/main.py#L86-L96).

If importing that module raises any kind of Python exception, the user sees a stack trace with a lot of unhelpful output.

For instance, if `demo.py` contains the line `asdf`, then we see:

```
$ DATABASE_URL=asdf python -m databuilder generate_dataset --dataset-definition demo.py
2022-06-04 21:34:55 [info     ] Generating dataset for demo.py [databuilder.main] 
Traceback (most recent call last):
  File "/home/inglesp/.pyenv/versions/3.9.5/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/inglesp/.pyenv/versions/3.9.5/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/inglesp/work/ebmdatalab/opensafely/databuilder/databuilder/__main__.py", line 179, in <module>
    main()
  File "/home/inglesp/work/ebmdatalab/opensafely/databuilder/databuilder/__main__.py", line 31, in main
    generate_dataset(
  File "/home/inglesp/work/ebmdatalab/opensafely/databuilder/databuilder/main.py", line 26, in generate_dataset
    dataset = load_definition(definition_file)
  File "/home/inglesp/work/ebmdatalab/opensafely/databuilder/databuilder/main.py", line 82, in load_definition
    load_module(definition_file)
  File "/home/inglesp/work/ebmdatalab/opensafely/databuilder/databuilder/main.py", line 97, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/inglesp/work/ebmdatalab/opensafely/databuilder/demo.py", line 1, in <module>
    asdf
NameError: name 'asdf' is not defined
```

In this case, only these lines are meaningful to the user:

```
2022-06-04 21:34:55 [info     ] Generating dataset for demo.py [databuilder.main] 
Traceback (most recent call last):
  File "/home/inglesp/work/ebmdatalab/opensafely/databuilder/demo.py", line 1, in <module>
    asdf
NameError: name 'asdf' is not defined
```

The [`traceback` module](https://docs.python.org/3/library/traceback.html#traceback.print_exception) contains functions for manipulating stack traces.  In particular, `traceback.format_exception(*sys.exc_info())` returns a list of lines of a stack trace.  It should be possible to filter out unhelpful lines from this list.  We can then write these lines to stderr and exit with an error code.

**Comment by CarolineMorton** [comment]
#609
