### ISSUE TITLE
Add a toggle to see full traceback on error

### ISSUE THREAD

**Issue by StevenMaude** [opensafely-core/databuilder#754]
From #711, Data Builder now has cleaner error messages. This is very helpful to prevent researchers from seeing lots of messages unrelated to their dataset definition.

Would a toggle to show the standard traceback still be useful for developer debugging?

## Example use case

This example was caused by me forgetting to update an import name inside my development documentation tables.[^1] The following message is all that was shown by Data Builder:

```
2022-09-28 09:28:18 [info     ] Generating dataset for databuilder/ehrql-tutorial-examples/1a_minimal_dataset_definition.py [databuilder.main]                                                                     
Traceback (most recent call last):                                                                                                                                                                                 
  File "databuilder/ehrql-tutorial-examples/1a_minimal_dataset_definition.py", line 2, in <module>                                                                                                                 
    from databuilder.tables.examples.tutorial import patient_demographics                                                                                                                                          
```

A more helpful error that points more directly to the problem is shown by the interpreter:

```
>>> from databuilder.tables.examples.tutorial import patient_demographics                                                                                                                                          
Traceback (most recent call last):                                                                                                                                                                                 
  File "<stdin>", line 1, in <module>                                                                                                                                                                              
  File "…/site-packages/databuilder/tables/examples/tutorial.py", line 1, in <module>                                   
    from databuilder.contracts.wip import (                                                                                                                                                                        
ImportError: cannot import name 'hospitalizations' from 'databuilder.contracts.wip' (…/site-packages/databuilder/contracts/wip.py)
```

I can accept that I may be the only person in the world using Data Builder like this, however.

[^1]: Because I'd updated the `hospitalisations` name in the [Data Builder code](https://github.com/opensafely-core/databuilder/pull/750), but [not in my development tables](https://github.com/opensafely-core/databuilder/commit/59354bcdd73cd2d252fa6af29f1cfa5b68e967b4).

**Comment by evansd** [comment]
Can you run the dataset definition module directly in Python? i.e.
```
python 1a_minimal_dataset_definition.py
```

That obviously relies on having databuilder installed locally but I think you do already, right?

**Comment by StevenMaude** [comment]
:arrow_up: yes, that works in this case to give a full import error, so maybe this isn't needed.
